package org.displaytag.tags;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.displaytag.test.DisplaytagCase;

import com.meterware.httpunit.GetMethodWebRequest;
import com.meterware.httpunit.HTMLElement;
import com.meterware.httpunit.WebRequest;
import com.meterware.httpunit.WebResponse;
import com.meterware.httpunit.WebTable;


/**
 * Tests for caption tag.
 * @author fgiust
 * @version $Revision$ ($Author$)
 */
public class CaptionTagTest extends DisplaytagCase
{

    /**
     * logger.
     */
    private static Log log = LogFactory.getLog(CaptionTagTest.class);


    /**
     * Instantiates a new test case.
     * @param name test name
     */
    public CaptionTagTest(String name)
    {
        super(name);
    }

    /**
     * Verifies that the generated page contains a table with a caption and checks all the caption html attributes.
     * @throws Exception any axception thrown during test.
     */
    public void testAutoGeneratedColumns() throws Exception
    {

        WebRequest request = new GetMethodWebRequest("http://localhost/caption.jsp");

        WebResponse response = runner.getResponse(request);

        log.debug("RESPONSE: " + response.getText());

        WebTable[] tables = response.getTables();

        assertEquals("Expected one table in result.", 1, tables.length);

        HTMLElement[] tags = response.getElementsWithName("caption");

        assertEquals("Expected one caption tag in result.", 1, tags.length);


        assertEquals("theid", tags[0].getID());
        assertEquals("theclass", tags[0].getClassName());
        assertEquals("thetitle", tags[0].getTitle());

    }
}
