package org.displaytag.tags;

import org.apache.commons.lang.StringUtils;
import org.displaytag.test.DisplaytagCase;

import com.meterware.httpunit.GetMethodWebRequest;
import com.meterware.httpunit.WebRequest;
import com.meterware.httpunit.WebResponse;
import com.meterware.httpunit.WebTable;


/**
 * Tests for caption tag.
 * @author Fabrizio Giustina
 * @version $Revision$ ($Author$)
 */
public class CaptionTagTest extends DisplaytagCase
{

    /**
     * Instantiates a new test case.
     * @param name test name
     */
    public CaptionTagTest(String name)
    {
        super(name);
    }

    /**
     * @see org.displaytag.test.DisplaytagCase#getJspName()
     */
    public String getJspName()
    {
        return "http://localhost/tld11/caption.jsp";
    }

    /**
     * Verifies that the generated page contains a table with a caption and checks all the caption html attributes.
     * @throws Exception any axception thrown during test.
     */
    public void testAutoGeneratedColumns() throws Exception
    {

        WebRequest request = new GetMethodWebRequest(getJspName());

        WebResponse response = runner.getResponse(request);

        log.debug("RESPONSE: " + response.getText());

        WebTable[] tables = response.getTables();

        assertEquals("Expected one table in result.", 1, tables.length);

        String output = response.getText();

        assertTrue("Caption tag missing", StringUtils.contains(output, "<caption"));

        assertTrue(StringUtils.contains(output, "class=\"theclass\""));
        assertTrue(StringUtils.contains(output, "dir=\"thedir\""));
        assertTrue(StringUtils.contains(output, "id=\"theid\""));
        assertTrue(StringUtils.contains(output, "lang=\"thelang\""));
        assertTrue(StringUtils.contains(output, "style=\"thestyle\""));
        assertTrue(StringUtils.contains(output, "title=\"thetitle\""));

    }
}