package org.displaytag.tags;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.displaytag.test.DisplaytagCase;

import com.meterware.httpunit.GetMethodWebRequest;
import com.meterware.httpunit.WebLink;
import com.meterware.httpunit.WebRequest;
import com.meterware.httpunit.WebResponse;


/**
 * Basic tests for pagination.
 * @author fgiust
 * @version $Revision$ ($Author$)
 */
public class PaginationTest extends DisplaytagCase
{

    /**
     * logger.
     */
    private static Log log = LogFactory.getLog(PaginationTest.class);

    /**
     * Instantiates a new test case.
     * @param name test name
     */
    public PaginationTest(String name)
    {
        super(name);
    }

    /**
     * @see org.displaytag.test.DisplaytagCase#getJspName()
     */
    public String getJspName()
    {
        return "http://localhost/tld11/pagination.jsp";
    }

    /**
     * Verifies that the generated page contains the pagination links with the inupt parameter. Tests #917200 ("{}" in
     * parameters).
     * @throws Exception any axception thrown during test.
     */
    public void testAutoGeneratedColumns() throws Exception
    {

        WebRequest request = new GetMethodWebRequest(getJspName());
        request.setParameter("{foo}", "/.,;:/||\\bar");

        WebResponse response = runner.getResponse(request);

        log.debug("RESPONSE: " + response.getText());

        WebLink[] links = response.getLinks();

        assertEquals("Wrong number of links in result.", 4, links.length);

        for (int j = 0; j < links.length; j++)
        {
            assertTrue(links[j].getURLString().indexOf("{foo}=%2F.%2C%3B%3A%2F%7C%7C%5Cbar") > -1);
            log.debug(j + " " + links[j].getURLString());
        }

    }
}